# Generated by Django 4.1 on 2022-08-04 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_name', models.CharField(max_length=100)),
                ('shift_type', models.CharField(choices=[('MO', 'Morning'), ('AF', 'Afternoon')], max_length=2)),
                ('observation_type', models.CharField(choices=[('NJ', 'New Journey'), ('JO', 'Journey'), ('ZO', 'Zonal')], max_length=2)),
                ('interaction_type', models.CharField(choices=[('INTPHY', 'Interaction with physician'), ('INTPAT', 'Interaction with patient'), ('INTNUR', 'Interaction with nurse'), ('INTOTH', 'Interaction with other'), ('PHONEC', 'Phone call'), ('CHARTI', 'Charting'), ('PROCED', 'Procedure'), ('DISCHA', 'Discharge'), ('PERSON', 'Personal'), ('WAITIN', 'Waiting'), ('OTHER1', 'Other'), ('MOVING', 'Moving')], default=None, max_length=6)),
                ('zone', models.CharField(choices=[('NUROPE', 'Nurse station open'), ('NURSTA', 'Nurse station'), ('NEUOFF', 'Neuro offices'), ('COCPIT', 'Cockpit'), ('CORRFT', 'Corridor Fast Track'), ('CORR01', 'Corridor 1'), ('CORR02', 'Corridor 2'), ('CORR03', 'Corridor 3'), ('CORR04', 'Corridor 4'), ('CORR05', 'Corridor 5'), ('CORR06', 'Corridor 6'), ('CORR07', 'Corridor 7')], default=None, max_length=6)),
                ('observation_start', models.DateTimeField()),
                ('observation_end', models.DateTimeField(auto_now=True)),
                ('badge_1', models.BooleanField()),
                ('badge_2', models.BooleanField()),
                ('badge_3', models.BooleanField()),
                ('badge_4', models.BooleanField()),
                ('badge_5', models.BooleanField()),
                ('badge_6', models.BooleanField()),
                ('badge_7', models.BooleanField()),
                ('badge_8', models.BooleanField()),
                ('badge_9', models.BooleanField()),
                ('badge_10', models.BooleanField()),
                ('badge_11', models.BooleanField()),
                ('badge_12', models.BooleanField()),
                ('badge_13', models.BooleanField()),
                ('badge_14', models.BooleanField()),
                ('badge_15', models.BooleanField()),
                ('badge_16', models.BooleanField()),
                ('badge_17', models.BooleanField()),
                ('badge_18', models.BooleanField()),
                ('badge_19', models.BooleanField()),
                ('badge_20', models.BooleanField()),
                ('badge_21', models.BooleanField()),
                ('badge_22', models.BooleanField()),
                ('badge_23', models.BooleanField()),
                ('badge_24', models.BooleanField()),
                ('badge_25', models.BooleanField()),
                ('prev_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collect.observationmodel')),
            ],
        ),
    ]
